apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
{{ include "chartName.labels" . | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "chartName.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}