{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "chartName.fullname" . }}"
  labels:
{{ include "chartName.labels" . | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "chartName.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "chartName.name" . }}
  minAvailable: {{ .Values.budget.minAvailable }}
{{- end -}}