apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "chartName.fullname" . }}
  labels:
{{ include "chartName.labels" . | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "chartName.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  privileged: {{ .Values.podSecurityPolicy.privileged }}
  allowPrivilegeEscalation: {{ .Values.podSecurityPolicy.allowPrivilegeEscalation }}
  requiredDropCapabilities:
   - ALL
  volumes:
    - 'configMap'
    - 'secret'
  hostNetwork: {{ .Values.podSecurityPolicy.hostNetwork }}
  hostIPC: {{ .Values.podSecurityPolicy.hostIPC }}
  hostPID: {{ .Values.podSecurityPolicy.hostPID }}
  readOnlyRootFilesystem: {{ .Values.podSecurityPolicy.readOnlyRootFilesystem }}
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostPorts:
  - max: 65535
    min: 1
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs