apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chartName.fullname" . }}
  labels:
{{ include "chartName.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "chartName.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "chartName.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}