{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chartName.serviceAccountName" . }}
  labels:
{{ include "chartName.labels" . | indent 4 }}
{{- end -}}