apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "wordpress.labels" . | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}